services:
  frontend:
    build:
      context: ./travelpoints_frontend
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - local-travelpoints-network


networks:
  local-travelpoints-network:
    name: local-travelpoints-network
    driver: bridge
